---
title: "R Notebook"
output: html_notebook
---
```{r}
ggplot((merge(merge(unwunifrac.pcoa$points, data.frame(holder$clustering), by = "row.names"), subset(metadados, !is.na(Region)), by.x = "Row.names", by.y = "Sample.id"))) + 
    geom_point(aes(x = V1, y = V2, color = paste(holder.clustering,Region), shape = as.character(Treponema)), size = 2) +
    labs(title = "UnWeighted Unifrac", x = "V1", y = "V2") +
    theme_minimal()

```


```{r}
ggplot((merge(merge(unwunifrac.pcoa$points, data.frame(holder$clustering), by = "row.names"), subset(metadados, !is.na(Region)), by.x = "Row.names", by.y = "Sample.id"))) + 
    geom_point(aes(x = V1, y = V2, color = paste(Treponema,Region), shape = as.character(holder.clustering)), size = 2) + 
    scale_color_manual("green", "blue", "red", "purple", "orange"), name = "Region") +
    labs(title = "UnWeighted Unifrac", x = "V1", y = "V2") +
    theme_minimal()
```


```{r}
merge(unwunifrac.pcoa$points, data.frame(holder$clustering), by = "row.names")
    

   merge(unwunifrac.pcoa$points, data.frame(holder$clustering)) 
  
   
   
```
    