---
title: "R Notebook"
output: html_notebook
---


```{r}
#preparando os dados pro ggplot

library(ggplot2)
library(dplyr)

# Preparando os dados


library(scales) # Para a função percent()


library(tidyr)  
```


```{r}
dados_saude <- metadados
```



```{r}
library(dplyr)

library(dplyr)

# Calcular média e desvio padrão da idade
age_summary <- metadados %>%
  summarise(
    mean_age = mean(Age, na.rm = TRUE),
    sd_age = sd(Age, na.rm = TRUE)
  )

# Visualizar os resultados
print(age_summary)
```


```{r}
# Criar um gráfico com média e desvio padrão
age_summary_long <- age_summary %>%
  pivot_longer(cols = everything(), names_to = "Statistic", values_to = "Value")
```


```{r}
library(ggplot2)
library(dplyr)
library(tidyr)


# Transformar os dados para o formato longo
age_summary_long <- age_summary %>%
  pivot_longer(cols = everything(), names_to = "Statistic", values_to = "Value")

# Criar o gráfico com média e desvio padrão
ggplot(age_summary_long, aes(x = Statistic, y = Value)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_errorbar(aes(ymin = Value - age_summary$sd_age, ymax = Value + age_summary$sd_age), width = 0.2) +
  labs(title = "Mean Age and Standard Deviation", x = NULL, y = "Age") +
  theme_minimal()


```


```{r}
# Calcular a quantidade de mulheres e homens
gender_counts <- metadados %>%
  group_by(Sex) %>%
  summarise(count = n())
```


```{r}
# Criar gráfico de barras para a quantidade de mulheres e homens
ggplot(gender_counts, aes(x = Sex, y = count, fill = Sex)) +
  geom_bar(stat = "identity") +
  labs(title = "Count of Women and Men", x = "Gender", y = "Count") +
  scale_fill_manual(values = c("Feminino" = "red", "Masculino" = "blue")) +
  theme_minimal()



```



```{r}



# Supondo que você tenha colunas chamadas HbA1c e HOMA em dados_saude
dados_saude <- metadados.dieta.saude.alpha %>%
  mutate(DIABETES = case_when(
    HbA1c >= 6.5 ~ "Diabetes",
    HbA1c >= 5.7 & HbA1c < 6.5 ~ "Pré-diabetes",
    HbA1c < 5.7 ~ "Normal",
    TRUE ~ NA_character_  # Para lidar com NAs ou valores inesperados
  ))

# Visualizar os dados com a nova coluna DIABETES
colnames (dados_saude)



```

```{r}
library(ggplot2)
library(dplyr)


# Garantir que a coluna DIABETES está corretamente mapeada como fator
dados_saude$DIABETES <- factor(dados_saude$DIABETES, levels = c("Diabetes", "Pré-diabetes", "Normal"))

# Calcular a quantidade e porcentagens de cada status de diabetes, removendo NAs
diabetes_counts <- dados_saude %>%
  filter(!is.na(DIABETES)) %>%  # Remove NAs
  group_by(DIABETES) %>%
  summarise(count = n()) %>%
  mutate(percentage = (count / sum(count)) * 100)  # Calcular porcentagens

# Criar o gráfico de pizza
ggplot(diabetes_counts, aes(x = "", y = count, fill = DIABETES)) +
  geom_bar(stat = "identity", width = 1) +  # Desenha o gráfico de barras
  coord_polar(theta = "y") +  # Converte para gráfico de pizza
  labs(title = "Diabetes Status Distribution", x = NULL, y = NULL, fill = "Status") +
  theme_void() +  # Remove a maioria dos elementos do tema
  scale_fill_manual(values = c("Diabetes" = "red", "Pré-diabetes" = "orange", "Normal" = "green")) +
  geom_label(aes(label = paste0(round(percentage, 1), "%")), position = position_stack(vjust = 0.5), color = "white", size = 5)

```



```{r}
# Renomear a coluna de ID em Agua_qualidade para facilitar a junção
colnames(Agua_qualidade)[colnames(Agua_qualidade) == "Sample-ID"] <- "SampleID"
```

```{r paged.print=TRUE}
# Realizar a junção
dados_combinados <- metadados %>%
  left_join(Agua_qualidade, by = "SampleID")  # Mantém todos os IDs de metadados

colnames(dados_combinados)
```
```{r}
#PieChart
ggplot(dados_saude, aes(x = "", fill = Group)) + 
  geom_bar(width = 1) + 
  coord_polar(theta = "y") +
  labs(title = "Distribuição dos Grupos SMet e NoSMet", x = NULL, y = NULL, fill = "Grupo") +
  theme_void()

#tirar NA
dados_saude <- dados_saude[!is.na(dados_saude$Group), ]
```
```{r}
# Carregar o pacote dplyr
library(dplyr)

# Remover as linhas que contêm NA nas colunas especificadas
metadados_filtrado <- metadados %>%
  filter(
    !is.na(Sex),
    !is.na(Waist),
    !is.na(Systolic),
    !is.na(Diastolic),
    !is.na(GLICOSE),
    !is.na(TRIGLICERIDES)
  )

# Criar a variável Group com base nas condições da síndrome metabólica
metadados_filtrado$Group <- ifelse(
  rowSums(
    cbind(
      (metadados_filtrado$Waist > 88 & metadados_filtrado$Sex == "Feminino") | (metadados_filtrado$Waist > 102 & metadados_filtrado$Sex == "Masculino"),
      metadados_filtrado$Systolic >= 130 | metadados_filtrado$Diastolic >= 85,
      metadados_filtrado$GLICOSE >= 110,
      metadados_filtrado$TRIGLICERIDES > 150,
      (metadados_filtrado$Sex == "Masculino" & metadados_filtrado$HDL < 40) | (metadados_filtrado$Sex == "Feminino" & metadados_filtrado$HDL < 50)
    )
  ) >= 3, "SMet", "NoSMet"
)


#tirar NA
metadados_filtrado <- metadados_filtrado[!is.na(metadados_filtrado), ]


# Verificar os primeiros resultados
head(metadados_filtrado$Group)

```

```{r}
frequencias <- table(metadados_filtrado$Group)

frequencias <- as.data.frame(frequencias)


#PieChart
ggplot(frequencias, aes(x = "", fill = Group)) + 
  geom_bar(width = 1) + 
  coord_polar(theta = "y") +
  labs(title = "Distribuição dos Grupos SMet e NoSMet", x = NULL, y = NULL, fill = "Grupo") +
  theme_void()

```

```{r}
# Converter as frequências em um data frame
frequencias_df <- data.frame(
  Group = c("NoSMet", "SMet"),
  Count = c(71, 34)
)
```


```{r}
# Criar o gráfico de pizza com cores diferentes para SMet e NoSMet
ggplot(frequencias_df, aes(x = "", y = Count, fill = Group)) + 
  geom_bar(stat = "identity", width = 1, color = "black") +  # Cor da borda preta
  coord_polar(theta = "y") +
  labs(title = "Distribution of Metabolic Syndrome", x = NULL, y = NULL, fill = "Group") +
  theme_void() +
  scale_fill_manual(values = c("NoSMet" = "lightblue", "SMet" = "tomato")) +  # Definir cores para cada grupo
  geom_text(aes(label = paste0(round(Count / sum(Count) * 100, 1), "%")), 
            position = position_stack(vjust = 0.5))

```


```{r}
# Filtrar dados para remover NAs
dados_filtrados <- dados_combinados %>%
  filter(!is.na(Parasitologico..) & !is.na(Type))

# Criar uma tabela de contingência entre as variáveis categóricas
tabela_contingencia <- table(dados_filtrados$Parasitologico.., dados_filtrados$Type)

# Realizar o teste qui-quadrado
resultado_qui2 <- chisq.test(table(dados_filtrados$Parasitologico.., dados_filtrados$Type))

# Realizar o teste exato de Fisher
resultado_fisher <- fisher.test(table(dados_filtrados$Parasitologico.., dados_filtrados$Type)

# Exibir o resultado
print(resultado_fisher)

# Criar a tabela de contingência
tabela_contingencia <- table(dados_filtrados$Parasitologico.., dados_filtrados$Type)

# Converter a tabela de contingência para um data frame
df_contingencia <- as.data.frame(tabela_contingencia)

# Criar o gráfico de barras com o valor p do teste Fisher
ggplot(df_contingencia, aes(x = Var2, y = Freq, fill = Var1)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Tipo de Fonte de Água", 
       y = "Frequência", 
       fill = "Parasitológico",
       title = "Distribuição do Parasitológico por Tipo de Fonte de Água") +
  theme_minimal() +
  # Adicionar o valor p ao gráfico
  annotate("text", x = 2, y = max(df_contingencia$Freq) + 2, 
           label = paste("p-valor do teste Fisher:", round(resultado_fisher$p.value, 4)), 
           size = 5, color = "red")

```

